name: 'CI'
on:
  push:

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install
        continue-on-error: false
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Test
        continue-on-error: false
        run: yarn test

      - name: Build Library
        continue-on-error: false
        run: yarn build

      - name: Upload Artifacts for Library
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: ./dist
          retention-days: 1

  deploy:
    needs: build
    if: github.event_name == 'push' && contains(github.ref, '/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Download Artifacts for Library
        continue-on-error: false
        uses: actions/download-artifact@v4
        with:
          name: library
          path: ./dist

      - name: NPM publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
